// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace PortalWeb_API.Models;

[Table("asignacion_equipos")]
public partial class AsignacionEquipos
{
    [Column("codequipo")]
    [StringLength(50)]
    [Unicode(false)]
    public string Codequipo { get; set; }

    [Column("coduser")]
    [StringLength(50)]
    [Unicode(false)]
    public string Coduser { get; set; }

    [Key]
    [Column("id")]
    public int Id { get; set; }

    [Column("fecrea", TypeName = "datetime")]
    public DateTime? Fecrea { get; set; }
}