// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace PortalWeb_API.Models;

[Keyless]
[Table("asignModUser")]
public partial class AsignModUser
{
    [Column("cod_user")]
    public int? CodUser { get; set; }

    [Column("cod_mod")]
    public int? CodMod { get; set; }

    [Column("state")]
    public int? State { get; set; }

    [Column("cod_cia")]
    [StringLength(45)]
    [Unicode(false)]
    public string CodCia { get; set; }

    [Column("order_mod")]
    public int? OrderMod { get; set; }

    [Column("permisos")]
    public int? Permisos { get; set; }
}