// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace PortalWeb_API.Models;

[Keyless]
public partial class ClienteSignaLocalidad
{
    [Column("id")]
    public int Id { get; set; }

    [Required]
    [Column("codigoCiente")]
    [StringLength(50)]
    [Unicode(false)]
    public string CodigoCiente { get; set; }

    [Required]
    [Column("master")]
    [StringLength(5)]
    [Unicode(false)]
    public string Master { get; set; }

    [Required]
    [Column("codigo")]
    [StringLength(20)]
    [Unicode(false)]
    public string Codigo { get; set; }

    [Column("fecrea", TypeName = "datetime")]
    public DateTime Fecrea { get; set; }
}