// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace PortalWeb_API.Models
{
    public partial class ConsolidadoSaldoCajas
    {
        [Key]
        public int id { get; set; }
        [Required]
        [StringLength(50)]
        [Unicode(false)]
        public string Fecha { get; set; }
        [Required]
        [StringLength(50)]
        [Unicode(false)]
        public string CodLocalidad { get; set; }
        [Required]
        [StringLength(50)]
        [Unicode(false)]
        public string Localidad { get; set; }
        [Required]
        [StringLength(50)]
        [Unicode(false)]
        public string CodCliente { get; set; }
        [Required]
        [StringLength(50)]
        [Unicode(false)]
        public string NomCliente { get; set; }
        [Required]
        [StringLength(50)]
        [Unicode(false)]
        public string CodEstablecimiento { get; set; }
        [Required]
        [StringLength(50)]
        [Unicode(false)]
        public string NomEstablecimiento { get; set; }
        [Required]
        [StringLength(50)]
        [Unicode(false)]
        public string Equipo { get; set; }
        [Column(TypeName = "decimal(18, 2)")]
        public decimal SaldoInicial { get; set; }
        [Column(TypeName = "decimal(18, 2)")]
        public decimal DepositosProcesados { get; set; }
        [Column(TypeName = "decimal(18, 2)")]
        public decimal Retiros { get; set; }
        [Column(TypeName = "decimal(18, 2)")]
        public decimal SaldoFinal { get; set; }
        [Required]
        [StringLength(50)]
        [Unicode(false)]
        public string NomArchivo { get; set; }
        [Required]
        [StringLength(1)]
        [Unicode(false)]
        public string Generado { get; set; }
        [Required]
        [StringLength(1)]
        [Unicode(false)]
        public string Active { get; set; }
    }
}