// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace PortalWeb_API.Models;

[Table("cuentaSignaTienda")]
public partial class CuentaSignaTienda
{
    [Key]
    [Column("id")]
    public int Id { get; set; }

    [Column("idtienda")]
    [StringLength(30)]
    public string Idtienda { get; set; }

    [Column("idcuentabancaria")]
    public int? Idcuentabancaria { get; set; }

    [Column("fcrea", TypeName = "datetime")]
    public DateTime? Fcrea { get; set; }
}