// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace PortalWeb_API.Models;

[Table("cuentas_bancarias")]
public partial class CuentasBancarias
{
    [Column("id")]
    public int Id { get; set; }

    [StringLength(50)]
    [Unicode(false)]
    public string CodigoCliente { get; set; }

    [Key]
    [Column("codcuentacontable")]
    [StringLength(50)]
    [Unicode(false)]
    public string Codcuentacontable { get; set; }

    [Column("nombanco")]
    [StringLength(250)]
    [Unicode(false)]
    public string Nombanco { get; set; }

    [Column("numerocuenta")]
    [StringLength(50)]
    [Unicode(false)]
    public string Numerocuenta { get; set; }

    [StringLength(50)]
    [Unicode(false)]
    public string TipoCuenta { get; set; }

    [Unicode(false)]
    public string Observacion { get; set; }

    [Column("fecrea", TypeName = "datetime")]
    public DateTime? Fecrea { get; set; }
}