// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace PortalWeb_API.Models;

[PrimaryKey("Id", "SerieEquipo")]
public partial class Equipos
{
    [Key]
    [Column("id")]
    public int Id { get; set; }

    [Column("codigoTiendaidFk")]
    public int CodigoTiendaidFk { get; set; }

    [Column("tipo")]
    [StringLength(80)]
    [Unicode(false)]
    public string Tipo { get; set; }

    [Column("marca")]
    [StringLength(80)]
    [Unicode(false)]
    public string Marca { get; set; }

    [Column("modelo")]
    [StringLength(50)]
    [Unicode(false)]
    public string Modelo { get; set; }

    [Key]
    [Column("serieEquipo")]
    [StringLength(50)]
    [Unicode(false)]
    public string SerieEquipo { get; set; }

    [Required]
    [Column("active")]
    [StringLength(1)]
    [Unicode(false)]
    public string Active { get; set; }

    [Column("capacidadIni")]
    public int? CapacidadIni { get; set; }

    [Column("capacidadFin")]
    public int? CapacidadFin { get; set; }

    [Column("fechaInstalacion", TypeName = "datetime")]
    public DateTime? FechaInstalacion { get; set; }

    [Column("estadoPing")]
    public int? EstadoPing { get; set; }

    [Column("tiempoSincronizacion", TypeName = "datetime")]
    public DateTime? TiempoSincronizacion { get; set; }

    [Column("fecrea", TypeName = "datetime")]
    public DateTime? Fecrea { get; set; }

    [Column("ultimaRecoleccion", TypeName = "datetime")]
    public DateTime? UltimaRecoleccion { get; set; }

    [Column("capacidadIniSobres")]
    public int? CapacidadIniSobres { get; set; }

    [Column("capacidadFinSobres")]
    public int? CapacidadFinSobres { get; set; }

    [StringLength(20)]
    [Unicode(false)]
    public string IpEquipo { get; set; }

    [Column("capacidadAsegurada")]
    public int? CapacidadAsegurada { get; set; }
}