// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace PortalWeb_API.Models;

[Table("errorAlerts")]
public partial class ErrorAlerts
{
    [Key]
    [Column("id")]
    public int Id { get; set; }

    [Column("nombre")]
    [StringLength(200)]
    [Unicode(false)]
    public string Nombre { get; set; }

    [Column("descripcion")]
    [StringLength(500)]
    [Unicode(false)]
    public string Descripcion { get; set; }

    [Column("fecrea", TypeName = "datetime")]
    public DateTime? Fecrea { get; set; }

    [Column("codusercrea")]
    [StringLength(100)]
    [Unicode(false)]
    public string Codusercrea { get; set; }

    [Column("active")]
    [StringLength(1)]
    [Unicode(false)]
    public string Active { get; set; }
}