// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace PortalWeb_API.Models
{
    public partial class marca
    {
        [Key]
        [StringLength(35)]
        [Unicode(false)]
        public string codigotipomaq { get; set; }
        [Key]
        [StringLength(5)]
        [Unicode(false)]
        public string codmarca { get; set; }
        [StringLength(250)]
        [Unicode(false)]
        public string nombremarca { get; set; }
    }
}