// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace PortalWeb_API.Models;

public partial class MasterEquipos
{
    [Column("id")]
    public int Id { get; set; }

    [Key]
    [StringLength(50)]
    [Unicode(false)]
    public string CodigoEquipo { get; set; }

    [StringLength(50)]
    [Unicode(false)]
    public string NombreEquipo { get; set; }

    public int? CapacidadBolsillo { get; set; }

    public int? VelocidadConteo { get; set; }

    [StringLength(1)]
    [Unicode(false)]
    public string Active { get; set; }
}