// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace PortalWeb_API.Models;

[PrimaryKey("Codigotipomaq", "Codmodelo", "Codmarca")]
[Table("modelo")]
public partial class Modelo
{
    [Key]
    [Column("codigotipomaq")]
    [StringLength(35)]
    [Unicode(false)]
    public string Codigotipomaq { get; set; }

    [Key]
    [Column("codmodelo")]
    [StringLength(5)]
    [Unicode(false)]
    public string Codmodelo { get; set; }

    [Key]
    [Column("codmarca")]
    [StringLength(5)]
    [Unicode(false)]
    public string Codmarca { get; set; }

    [Column("nombremodelo")]
    [StringLength(250)]
    [Unicode(false)]
    public string Nombremodelo { get; set; }
}