// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace PortalWeb_API.Models;

public partial class ModulosApp
{
    [Column("nombre_module")]
    [StringLength(150)]
    [Unicode(false)]
    public string NombreModule { get; set; }

    [Column("description_module")]
    [StringLength(500)]
    [Unicode(false)]
    public string DescriptionModule { get; set; }

    [Column("icon_module")]
    [StringLength(15)]
    [Unicode(false)]
    public string IconModule { get; set; }

    [Column("color_module")]
    [StringLength(20)]
    [Unicode(false)]
    public string ColorModule { get; set; }

    [Column("order_module")]
    public int? OrderModule { get; set; }

    [Column("estate_module")]
    public int? EstateModule { get; set; }

    [Key]
    [Column("id_module")]
    public int IdModule { get; set; }
}