// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace PortalWeb_API.Models
{
    public partial class NumeroCortesDias
    {
        [Key]
        public int id { get; set; }
        [Required]
        [StringLength(50)]
        [Unicode(false)]
        public string Fecha { get; set; }
        public int NumCorte { get; set; }
        [Required]
        [StringLength(1)]
        [Unicode(false)]
        public string Active { get; set; }
    }
}