// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace PortalWeb_API.Models
{
    public partial class SP_CalculoTotalResult
    {
        [Column("Total", TypeName = "decimal(38,2)")]
        public decimal? Total { get; set; }
    }
}
