// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace PortalWeb_API.Models
{
    public partial class SP_ConsolidadoLocalidadResult
    {
        public string NombreCliente { get; set; }
        public string NombreTienda { get; set; }
        public string Localidad { get; set; }
        public string Machine_Sn { get; set; }
        public string Establecimiento { get; set; }
        public string CodigoEstablecimiento { get; set; }
        public string numerocuenta { get; set; }
        public string Observacion { get; set; }
        [Column("Total", TypeName = "decimal(38,2)")]
        public decimal? Total { get; set; }
    }
}
