// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace PortalWeb_API.Models
{
    public partial class SP_DatosEquiposFrontResult
    {
        public string Tipo { get; set; }
        public int? DepositoCant100 { get; set; }
        public int? DepositoCant50 { get; set; }
        public int? DepositoCant20 { get; set; }
        public int? DepositoCant10 { get; set; }
        public int? DepositoCant5 { get; set; }
        public int? DepositoCant2 { get; set; }
        public int? DepositoCant1 { get; set; }
        public int? DepositoMont100 { get; set; }
        public int? DepositoMont50 { get; set; }
        public int? DepositoMont20 { get; set; }
        public int? DepositoMont10 { get; set; }
        public int? DepositoMont5 { get; set; }
        public int? DepositoMont2 { get; set; }
        public int? DepositoMont1 { get; set; }
        public decimal? DepositoCantCoin100 { get; set; }
        public decimal? DepositoCantCoin50 { get; set; }
        public decimal? DepositoCantCoin25 { get; set; }
        public decimal? DepositoCantCoin10 { get; set; }
        public decimal? DepositoCantCoin5 { get; set; }
        public decimal? DepositoCantCoin1 { get; set; }
        public decimal? DepositoMontCoin100 { get; set; }
        public decimal? DepositoMontCoin50 { get; set; }
        public decimal? DepositoMontCoin25 { get; set; }
        public decimal? DepositoMontCoin10 { get; set; }
        public decimal? DepositoMontCoin5 { get; set; }
        public decimal? DepositoMontCoin1 { get; set; }
    }
}
