// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace PortalWeb_API.Models
{
    public partial class SP_EquiposNoTransaccionesResult
    {
        public string Machine_Sn { get; set; }
        public int? NoTransaccion { get; set; }
    }
}
