// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace PortalWeb_API.Models
{
    public partial class SP_EquiposNoTransaccionesResult
    {
        public string Machine_Sn { get; set; }
        public string IpEquipo { get; set; }
        public string NombreTienda { get; set; }
        public string Localidad { get; set; }
        public int? codigoTiendaidFk { get; set; }
        public string idCliente { get; set; }
        public int? idCliente2 { get; set; }
        public int Conteo_M { get; set; }
        public int Conteo_A { get; set; }
        public int Conteo_R { get; set; }
        public int Conteo_MR { get; set; }
        public int Conteo_AR { get; set; }
    }
}
