// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace PortalWeb_API.Models
{
    public partial class SP_GraficoTotalesAñoResult
    {
        public int? Transaccion_No { get; set; }
        public string Usuarios_idFk { get; set; }
        public DateTime? FechaTransaccion { get; set; }
        public int? CantidadBilletes { get; set; }
        public int? CantidadMoneda { get; set; }
        [Column("TotalBilletes", TypeName = "decimal(10,2)")]
        public decimal? TotalBilletes { get; set; }
        [Column("TotalMonedas", TypeName = "decimal(10,2)")]
        public decimal? TotalMonedas { get; set; }
        [Column("Total", TypeName = "decimal(10,2)")]
        public decimal? Total { get; set; }
        public string Tipo { get; set; }
    }
}
