// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace PortalWeb_API.Models
{
    public partial class SP_ObtenerTotalesMachinResult
    {
        public DateTime? FechaTransaccion { get; set; }
        [Column("TotalRecoleccion", TypeName = "decimal(38,2)")]
        public decimal? TotalRecoleccion { get; set; }
        public string TipoTransaccion { get; set; }
    }
}
