// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace PortalWeb_API.Models
{
    public partial class SP_ObtenerEquipoTempResult
    {
        public string serieEquipo { get; set; }
        public string IpEquipo { get; set; }
    }
}
