// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace PortalWeb_API.Models
{
    public partial class sp_obtener_maquinariaResult
    {
        public int? idCliente { get; set; }
        public string NombreCliente { get; set; }
        public string NombreTienda { get; set; }
        public string TelfAdmin { get; set; }
        public string tipoMaquinaria { get; set; }
        public string nombremarca { get; set; }
        public string nombremodelo { get; set; }
        public int? id { get; set; }
        public int? codigoTiendaidFk { get; set; }
        public string CodigoTienda { get; set; }
        public int? capacidadAsegurada { get; set; }
        public string tipo { get; set; }
        public string marca { get; set; }
        public string modelo { get; set; }
        public string serieEquipo { get; set; }
        public string active { get; set; }
        public int? capacidadIni { get; set; }
        public DateTime? fechaInstalacion { get; set; }
        public int? estadoPing { get; set; }
        public int? capacidadFin { get; set; }
        public DateTime? tiempoSincronizacion { get; set; }
        public DateTime? fecrea { get; set; }
        public DateTime? ultimaRecoleccion { get; set; }
        public int? capacidadIniSobres { get; set; }
        public int? capacidadFinSobres { get; set; }
        public int? capacidadUsuariosTemporales { get; set; }
        public int? capacidadUsuarios { get; set; }
        public string provincia { get; set; }
        public string IpEquipo { get; set; }
    }
}
