// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace PortalWeb_API.Models
{
    public partial class TotalesEquipos
    {
        [Key]
        public int id { get; set; }
        [Required]
        [StringLength(50)]
        [Unicode(false)]
        public string Equipo { get; set; }
        public int? UltimaTransaccion { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? FechaUltimaTransaccion { get; set; }
        [StringLength(1)]
        [Unicode(false)]
        public string Tipo { get; set; }
        public int? TotalEquipoManualCoin1 { get; set; }
        public int? TotalEquipoManualCoin5 { get; set; }
        public int? TotalEquipoManualCoin10 { get; set; }
        public int? TotalEquipoManualCoin25 { get; set; }
        public int? TotalEquipoManualCoin50 { get; set; }
        public int? TotalEquipoManualCoin100 { get; set; }
        public int? TotalEquipoManualBill1 { get; set; }
        public int? TotalEquipoManualBill2 { get; set; }
        public int? TotalEquipoManualBill5 { get; set; }
        public int? TotalEquipoManualBill10 { get; set; }
        public int? TotalEquipoManualBill20 { get; set; }
        public int? TotalEquipoManualBill50 { get; set; }
        public int? TotalEquipoManualBill100 { get; set; }
        public int? TotalEquipoDepositoBill1 { get; set; }
        public int? TotalEquipoDepositoBill2 { get; set; }
        public int? TotalEquipoDepositoBill5 { get; set; }
        public int? TotalEquipoDepositoBill10 { get; set; }
        public int? TotalEquipoDepositoBill20 { get; set; }
        public int? TotalEquipoDepositoBill50 { get; set; }
        public int? TotalEquipoDepositoBill100 { get; set; }
        public int? EquipoDepositoBill1 { get; set; }
        public int? EquipoDepositoBill2 { get; set; }
        public int? EquipoDepositoBill5 { get; set; }
        public int? EquipoDepositoBill10 { get; set; }
        public int? EquipoDepositoBill20 { get; set; }
        public int? EquipoDepositoBill50 { get; set; }
        public int? EquipoDepositoBill100 { get; set; }
        public int? EquipoManualBill1 { get; set; }
        public int? EquipoManualBill2 { get; set; }
        public int? EquipoManualBill5 { get; set; }
        public int? EquipoManualBill10 { get; set; }
        public int? EquipoManualBill20 { get; set; }
        public int? EquipoManualBill50 { get; set; }
        public int? EquipoManualBill100 { get; set; }
        public int? EquipoManualCoin1 { get; set; }
        public int? EquipoManualCoin5 { get; set; }
        public int? EquipoManualCoin10 { get; set; }
        public int? EquipoManualCoin25 { get; set; }
        public int? EquipoManualCoin50 { get; set; }
        public int? EquipoManualCoin100 { get; set; }
        [Column(TypeName = "decimal(16, 2)")]
        public decimal? TotalCuadreEquipo { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? FechaUltimaRecoleccion { get; set; }
    }
}