// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace PortalWeb_API.Models
{
    public partial class TransaccionesExcel
    {
        [Key]
        public int ID { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? FechaTransaccion { get; set; }
        [Column(TypeName = "date")]
        public DateTime? Fecha { get; set; }
        [StringLength(50)]
        public string Hora { get; set; }
        [StringLength(255)]
        public string NombreCliente { get; set; }
        [StringLength(255)]
        public string NombreTienda { get; set; }
        public int? Transaccion_No { get; set; }
        [StringLength(50)]
        public string Machine_Sn { get; set; }
        [StringLength(50)]
        public string Usuarios_idFk { get; set; }
        [StringLength(255)]
        public string Establecimiento { get; set; }
        [StringLength(50)]
        public string CodigoEstablecimiento { get; set; }
        [StringLength(255)]
        public string nombanco { get; set; }
        [StringLength(50)]
        public string TipoCuenta { get; set; }
        [StringLength(50)]
        public string numerocuenta { get; set; }
        [StringLength(255)]
        public string Observacion { get; set; }
        public int? Deposito_Bill_1 { get; set; }
        public int? Deposito_Bill_2 { get; set; }
        public int? Deposito_Bill_5 { get; set; }
        public int? Deposito_Bill_10 { get; set; }
        public int? Deposito_Bill_20 { get; set; }
        public int? Deposito_Bill_50 { get; set; }
        public int? Deposito_Bill_100 { get; set; }
        public int? Manual_Deposito_Coin_1 { get; set; }
        public int? Manual_Deposito_Coin_5 { get; set; }
        public int? Manual_Deposito_Coin_10 { get; set; }
        public int? Manual_Deposito_Coin_25 { get; set; }
        public int? Manual_Deposito_Coin_50 { get; set; }
        public int? Manual_Deposito_Coin_100 { get; set; }
        [Column(TypeName = "decimal(10, 2)")]
        public decimal? Total { get; set; }
        [StringLength(1)]
        [Unicode(false)]
        public string Repetido { get; set; }
        [StringLength(50)]
        public string TipoTransaccion { get; set; }
        [StringLength(1)]
        [Unicode(false)]
        public string Acreditada { get; set; }
    }
}